# Site settings
title: Omniscient.js
description: > # this means to ignore newlines until "baseurl:"
  A library providing an abstraction for React components that allows for
  fast top-down rendering embracing immutable data for js.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://omniscientjs.github.io/" # the base hostname & protocol for your site

version: 4.0.0

# Build settings
markdown: kramdown

exclude:
 - node_modules

collections:
  api:
    output: true
    collection: API
    permalink: /api/:path/
  guides:
    output: true
    collection: Guides
    permalink: /guides/:path/
  playground:
    output: true
    collection: Playground
    permalink: /playground/:path/
  workshop:
    hide: true
    output: true
    collection: Workshop
    permalink: /workshop/:path/
  tutorials:
    output: true
    collection: Tutorials
    permalink: /tutorials/:path/

permalink: pretty

kramdown:
  input: GFM
  hard_wrap: false
